### ISSUE TITLE
Please add you adapter to our repository

### ISSUE THREAD

**Issue by ioBrokerChecker** [shady2k/ioBroker.zabbix#2]
We saw your adapter and if it is ready please request that it is added to the repository. With this it becomes available for all users. Please consult https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository and the following sections for more details.
If you need help, contact us in the forum https://forum.iobroker.net/ or in the developer chat https://github.com/iobroker-community-adapters/info .

Thank you for your support.

**Comment by Apollon77** [comment]
@shady2k Does that mean you do not plan to add the adapter to the official repository ... It would be very interesting to know why?

**Comment by shady2k** [comment]
Let my try to explain. This adapter was developed for my needs. There is a lot of requirements to add in your repository. If you need iobroker.zabbix name, I can rename it.

**Comment by Apollon77** [comment]
In the end your decision ... Users will find it and use it ... So mabe add something in your Readme that makes it clear.

**Comment by shady2k** [comment]
Sorry, I don't understand what do you mean. What should I add to readme? Information about why I don't want this adapter to your repo?

**Comment by Apollon77** [comment]
Add an info to teh Readme that tells users that found the adapter that this is just work for you and that you will not support anything ... else users might think that it is "Just not 100% ready" :-)
